### PR TITLE
Add PeriodCollection to fetch gaps within time

### PR DESCRIPTION
**Pull request by jackdpeterson**
## Introduction

Add the ability to perform inversion and linear sorting off of a collection of Periods.

### Describe the new/updated/fixed feature

PeriodCollection->invert() --> given a collection of periods ... find the gaps between all of them.
PeriodCollection->sort(false) --> sort from earliest to latest
PeriodCollection->sort(true) --> sort form earliest to latest and converge periods that contain eachother.

### Targeted release version
Next minor.

### PR Impact

New functionality added to a new class.

## Open issues
Currently relies on PHP 7+ with the declared strict types.

### CODE REVIEW

**Comment by jackdpeterson** [comment]
Resolves #47 
This is probably a naive implementation and peer review is requested.

**Comment by jackdpeterson** [comment]
This also resolves #46

**Comment by nyamsprod** [comment]
@jackdpeterson thanks for submitting you PR. I never thought of adding a collection to the package because IMHO this is easy to implements using PHP SPL classes. Something along this line would met all requirement with little code added 

```php
use League\Period\Period;

class PeriodCollection extends ArrayIterator
{
    public function __construct($collection)
    {
        $periods = (function (Period ...$collection) {
            return $collection;
        })(...$collection);

        parent::__construct($periods);
    }

    public function offsetSet($index, $newval)
    {
        if (!$newval instanceof Period) {
            throw new InvalidArgumentException;
        }

        parent::offsetSet($index, $newval);
    }
}
```
With this simple class, we remove all the special cases you've added to resolve #47 and you can still resolve it using your own business logic with something along this line.

```php
$sort = function (Period $periodA, Period $periodB) {
    if ($periodA->isBefore($periodB)) {
        return -1;
    }

    if ($periodA->isAfter($periodB)) {
        return 1;
    }

    return 0;
};
$period_reference = //a period reference defines in your business logic
$filter = function (Period $current) use ($period_reference) {
    return $period_reference->contains($current);
};

$collection = new PeriodCollection($periods);
$collection->uasort($sort);
$orderedPeriods = new CallbackFilterIterator($collection, $filter );
var_dump(iterator_to_array($orderedPeriods));
```

Voila. To me this is a better implementation and again all these steps are straightforward and do not need to be put into the package unless proven otherwise.

**Comment by jackdpeterson** [comment]
I get where you're coming form here. One bit of functionality that you didn't mention above (as far as I cna tell) which is really the problem that I was solving for is the Collection->invert() functionality ... effectively finding the relevant gaps within the provided collection of periods. The real-world version of this is given a calendar with booked appointment periods ... I want to get the available periods within a given period (an entire day). Hence the whole collection thing and the two new functions, sort(true) and invert().

I suppose my thinking is that adding the support for collections (whether through the SPL parent classes or otherwise) is that having a standard, unit-tested mechanism for that functionality could be part of this library. Much like providing a Repository interface makes an Entity manager more robust.

**Comment by nyamsprod** [comment]
@jackdpeterson Indeed I took the easiest example but implementing the `invert` method is *just* about improving the `$filter` method with your business requirement. 
The main point of my argument is to show that the `Period` class is the basic block from which you can build other tool like a Period collection or a Calendar system which would require IMHO their own package/library because they are indeed more complex to build properly.
I'd rather focus on make the best Period class than an average Calendar system.

**Comment by jackdpeterson** [comment]
Cool -- I'm good with that. Makes sense to me. Thanks for the review and comments!

**Comment by nyamsprod** [comment]
@jackdpeterson Just to let you know I'm currently in process on adding new functionnalities to the next Period version .... and a [Collection interface](https://github.com/thephpleague/period/blob/master/src/Collection.php) has been added with a implementation called [Sequence](https://github.com/thephpleague/period/blob/master/src/Sequence.php).

```php
<?php

use League\Period\Period;
use League\Period\Sequence;

$collection = new Sequence();
$collection['sports'] = Period::createFromHour('2018-07-31 12:00:00');
$collection['meeting'] = Period::createFromDurationAfterStart('2018-07-31 14:00:00, '3 HOURS');
$collection->getGaps(); //returns a Sequence object with the 1 HOUR gaps
```

The sequence can also do other stuffs. the main reason it has been added is because using available collections. Comparisons are always done by ref while since Period is immutable, comparisons should be done using the object value.

**Warning:** A sequence is not a full Calendar but one can easily use it as a backbone to create such object.

**Pull request closed without merging**
